[package]
name = "force"
version = "0.1.0"
authors = ["MROS <yc1043@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
regex = "1.3.7"
